# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [92]:
import numpy as np
arr1 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print ("The 1D array is :",(arr1))
arr2d = arr1.reshape(2,5)
arr2d

The 1D array is : [0 1 2 3 4 5 6 7 8 9]


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [24]:
arr1 = np.arange(10).reshape(2,5)
arr2 = np.ones((2,5), dtype= "int")
desired_array = np.vstack((arr1, arr2))
desired_array

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [25]:
arr1 = np.arange(10).reshape(2,5)
arr2 = np.ones((2,5), dtype= "int")
desired_array = np.hstack((arr1, arr2))
desired_array

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [37]:
arr1 = np.arange(10).reshape(2,5)
flattened_array = arr1.flatten()
flattened_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [40]:
arr1 = np.arange(15).reshape(3,5)
D1array = arr1.ravel()
D1array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [43]:
array1 = np.arange(15).reshape(5,3)
array1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [49]:
array = np.arange(25).reshape(5,5)
arr2 = np.square(array)
arr2

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361],
       [400, 441, 484, 529, 576]], dtype=int32)

## Question:8

### Create 5x6 an array and find the mean?

In [53]:
array = np.arange(30).reshape(5,6)
arr2 = np.mean(array)
arr2

14.5

## Question:9

### Find the standard deviation of the previous array in Q8?

In [54]:
array = np.arange(30).reshape(5,6)
arr2 = np.std(array)
arr2

8.65544144839919

## Question:10

### Find the median of the previous array in Q8?

In [55]:
array = np.arange(30).reshape(5,6)
arr2 = np.median(array)
arr2

14.5

## Question:11

### Find the transpose of the previous array in Q8?

In [59]:
array = np.arange(30).reshape(5,6)
arr2 = array.T
arr2

array([[ 0,  6, 12, 18, 24],
       [ 1,  7, 13, 19, 25],
       [ 2,  8, 14, 20, 26],
       [ 3,  9, 15, 21, 27],
       [ 4, 10, 16, 22, 28],
       [ 5, 11, 17, 23, 29]])

## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [72]:
array = np.arange(0,32,2).reshape(4,4)
print(array)
arr2 = np.trace(array)
arr2

[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]
 [24 26 28 30]]


60

## Question:13

### Find the determinant of the previous array in Q12?

In [86]:
array = np.arange(0,32,2).reshape(4,4)
print(array)
arr2 = np.linalg.det(array)
arr2

[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]
 [24 26 28 30]]


0.0

## Question:14

### Find the 5th and 95th percentile of an array?

In [151]:
a=np.array([[10, 7, 4],[3, 2, 1]])
print(np.percentile(a,5))
print(np.percentile(a,95))


1.25
9.25


## Question:15

### How to find if a given array has any null values?

In [148]:
arr1 = np.ones((2,2))
arr1[0]=np.nan
print(arr1)
np.any(np.nan)



[[nan nan]
 [ 1.  1.]]


True