# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [2]:
import numpy as np

2. Create a null vector of size 10 

In [6]:
null_vector = np.zeros(10, dtype = "int")
null_vector

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

3. Create a vector with values ranging from 10 to 49

In [8]:
vect= np.arange(10,50)
vect

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

4. Find the shape of previous array in question 3

In [9]:
np.shape(vect)

(40,)

5. Print the type of the previous array in question 3

In [10]:
type(vect)

numpy.ndarray

6. Print the numpy version and the configuration


In [14]:
print(np.__version__)
print(np.show_config())

1.19.2
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Rafay/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Rafay/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Rafay/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Rafay/anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Rafay/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Rafay/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Rafay/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Rafay/anaconda3\\Library\\include']
None


7. Print the dimension of the array in question 3


In [15]:
print(vect.ndim)

1


8. Create a boolean array with all the True values

In [19]:
boolarray = np.ones((2,2), dtype = "bool")
boolarray

array([[ True,  True],
       [ True,  True]])

9. Create a two dimensional array




In [20]:
d2array = np.arange(6).reshape(2,3)
d2array

array([[0, 1, 2],
       [3, 4, 5]])

10. Create a three dimensional array



In [21]:
d3array = np.arange(24).reshape(2,4,3)
d3array

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [23]:
vect1 = np.arange(5)
print("original vector", vect1)
reverse_vector = np.flipud(vect1)
print("Reversed vector", reverse_vector)

original vector [0 1 2 3 4]
Reversed vector [4 3 2 1 0]


12. Create a null vector of size 10 but the fifth value which is 1 

In [26]:
null_vector = np.zeros(10,dtype="int")
null_vector[4] = 1
null_vector

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

13. Create a 3x3 identity matrix

In [42]:
I3matrix = np.identity(3, dtype=int)
print(I3matrix)
print("The dimension of above identity matrix is",I3matrix.ndim)
d3matrix = I3matrix.reshape(1,3,3)
print(d3matrix)
print("The dimension of three dimension identity matrix is",d3matrix.ndim)

[[1 0 0]
 [0 1 0]
 [0 0 1]]
The dimension of above identity matrix is 2
[[[1 0 0]
  [0 1 0]
  [0 0 1]]]
The dimension of three dimension identity matrix is 3


14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [43]:
float_array = np.array([1,2,3,4,5], dtype="float")
print(float_array)

[1. 2. 3. 4. 5.]


15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [50]:
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]])  
arr2 = np.array([[0., 4., 1.],

           [7., 2., 12.]])
res = arr1.dot(arr2)
print(res)

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [53]:
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]]) 
arr2 = np.array([[0., 4., 1.],

            [7., 2., 12.]])
ndarray = arr1 == arr2
newarray = ndarray.all()
print(newarray)


False


17. Extract all odd numbers from arr with values(0-9)

In [60]:
array = np.arange(10)
print("The array is",array)
odd_array = array[1:10:2]
print("Odd numbers are",odd_array)

The array is [0 1 2 3 4 5 6 7 8 9]
Odd numbers are [1 3 5 7 9]


18. Replace all odd numbers to -1 from previous array

In [65]:
array = np.arange(10)
print("The array is",array)
odd_array = array[1:10:2]
print("Odd numbers are",odd_array)
odd_array[0:5] = -1
print("Replaced odd numbers with -1",odd_array)
print("The original array becomes now",array)


The array is [0 1 2 3 4 5 6 7 8 9]
Odd numbers are [1 3 5 7 9]
Replaced odd numbers with -1 [-1 -1 -1 -1 -1]
The original array becomes now [ 0 -1  2 -1  4 -1  6 -1  8 -1]


19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [66]:
arr = np.arange(10)
arr[5:9] =12
print(arr)

[ 0  1  2  3  4 12 12 12 12  9]


20. Create a 2d array with 1 on the border and 0 inside

In [68]:
d2array = np.array([[1, 1, 1],[1,0, 1],[1,1,1]])
print(d2array)

[[1 1 1]
 [1 0 1]
 [1 1 1]]


Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [73]:
arr2d = np.array([[1, 2, 3],

            [4, 5, 6], 

            [7, 8, 9]])
arr2d[1,1] = 12
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [77]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr3d) 
print("============================")
arr3d[0] =64
print(arr3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[[[64 64 64]
  [64 64 64]]

 [[ 7  8  9]
  [10 11 12]]]


23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [85]:
d2array =np.arange(10).reshape(2,5)

print(d2array[0])

[0 1 2 3 4]


24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [90]:
d2array =np.arange(10).reshape(2,5)
print(d2array)
print("The 2nd value from 2nd 1-D array  is 6 : ",d2array[1:,1:2])

[[0 1 2 3 4]
 [5 6 7 8 9]]
The 2nd value from 2nd 1-D array  is 6 :  [[6]]


25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [98]:
d2array =np.arange(10).reshape(2,5)
print(d2array)
print(d2array[0:2,2:3])

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[2]
 [7]]


26. Create a 10x10 array with random values and find the minimum and maximum values

In [106]:
x = np.random.random((10,10))
print("Original Array:")
print(x) 
xmin, xmax = x.min(), x.max()
print("Minimum and Maximum Values:")
print(xmin, xmax)

Original Array:
[[0.79621655 0.68616972 0.23930232 0.79864204 0.67189044 0.46018476
  0.53060466 0.46240954 0.96185422 0.42006399]
 [0.73601845 0.04963688 0.22770468 0.93580443 0.19324351 0.98291563
  0.00760036 0.86230473 0.8421181  0.31503371]
 [0.16003911 0.85413622 0.37786357 0.46959632 0.07098304 0.17511669
  0.63090842 0.6620201  0.75855828 0.42215295]
 [0.04803918 0.40074709 0.16332959 0.17850643 0.0319966  0.4605457
  0.84075551 0.08039615 0.1681122  0.98313495]
 [0.64612151 0.4257284  0.76512465 0.2424692  0.86907494 0.39246054
  0.1556014  0.83967224 0.74840072 0.71111813]
 [0.85826906 0.95836091 0.06594532 0.4334133  0.25993577 0.84835816
  0.60017243 0.03854214 0.7452855  0.94082279]
 [0.9846353  0.8667901  0.79249251 0.76615346 0.67409234 0.58717076
  0.77221544 0.37883204 0.00554228 0.92062828]
 [0.13310565 0.21856402 0.80931414 0.49420948 0.39477199 0.80059464
  0.23170119 0.08922974 0.85865266 0.54635659]
 [0.58147655 0.2345543  0.97561475 0.00446442 0.42559794 0.152555

27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [107]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
common_items = np.intersect1d(a,b)
print(common_items)

[2 4]


28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [112]:
 a= np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
common_items = np.intersect1d(a,b)
print("The common items are:",common_items)
print("The  positions where elements of a and b match :",np.argwhere(a==b))


The common items are: [2 4]
The  positions where elements of a and b match : [[1]
 [3]
 [5]
 [7]]


29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [16]:
import numpy as np
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
print(names)
print(data)
data[names != "Will"]


['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']
[[ 0.44285334  0.36629046 -0.50809913 -1.21045203]
 [-0.56523595 -0.77715438  0.19541988 -0.27063348]
 [-0.86176421 -0.52545571  2.40465475 -0.8810829 ]
 [-0.01833457  0.48648263  0.58305352  1.21725781]
 [ 0.66205103  0.68755371  2.22108099 -0.81321689]
 [-0.16078105 -2.89259937  0.48648189 -0.40461735]
 [-0.74338923 -1.24829942  0.17175308  0.71704824]]


array([[ 0.44285334,  0.36629046, -0.50809913, -1.21045203],
       [-0.56523595, -0.77715438,  0.19541988, -0.27063348],
       [-0.01833457,  0.48648263,  0.58305352,  1.21725781],
       [-0.16078105, -2.89259937,  0.48648189, -0.40461735],
       [-0.74338923, -1.24829942,  0.17175308,  0.71704824]])

30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [19]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
compare = (names != "Will") & (names != "Joe")
print(compare)
print(data[compare])


[ True False False  True False False False]
[[-0.61001728  1.29690989  0.54898212  0.38311296]
 [-1.62446931  0.23957964  0.86224643  0.84830595]]


Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [26]:
d2array=np.arange(1.5,16.5).reshape(5,3)
d2array

array([[ 1.5,  2.5,  3.5],
       [ 4.5,  5.5,  6.5],
       [ 7.5,  8.5,  9.5],
       [10.5, 11.5, 12.5],
       [13.5, 14.5, 15.5]])

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [28]:
d3array=np.arange(1.5,17.5).reshape(2,2,4)
d3array

array([[[ 1.5,  2.5,  3.5,  4.5],
        [ 5.5,  6.5,  7.5,  8.5]],

       [[ 9.5, 10.5, 11.5, 12.5],
        [13.5, 14.5, 15.5, 16.5]]])

33. Swap axes of the array you created in Question 32

In [116]:
d3array=np.arange(1,17).reshape(2,2,4)
print(d3array)
c= np.swapaxes(d3array,1,2)
c

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]


array([[[ 1,  5],
        [ 2,  6],
        [ 3,  7],
        [ 4,  8]],

       [[ 9, 13],
        [10, 14],
        [11, 15],
        [12, 16]]])

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [49]:
arr= np.arange(10)
sqrt_1 = np.sqrt(arr)
print(sqrt_1)

[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]


35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [53]:
arr1 =np.array([1, 2, 3])
arr2 =np.array([4,5,6])
a = np.amax(arr1)
b= np.amax(arr2)
max_array = np.array([a,b])
print(max_array)



[3 6]


36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [55]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
u = np.unique(names)
print(u)
                 

['Bob' 'Joe' 'Will']


37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [58]:
a = np.array([1,2,3,4,5]) 
b = np.array([5,6,7,8,9])

result = np.setdiff1d(a, b)
print("a = ",result)


a =  [1 2 3 4]


38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [100]:
x= np.array([[34, 43,73],[82, 22, 12],[53, 94, 66]])
print(x)
x=np.delete(x,1,1)
print(x)
np.insert(x,1,10, axis =1)


[[34 43 73]
 [82 22 12]
 [53 94 66]]
[[34 73]
 [82 12]
 [53 66]]


array([[34, 10, 73],
       [82, 10, 12],
       [53, 10, 66]])

39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [101]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
print(x.dot(y))

[[ 28.  64.]
 [ 67. 181.]]


40. Generate a matrix of 20 random values and find its cumulative sum

In [106]:
x= np.random.randn(20)
y=np.sum(x)
print(y)

4.0550848435208104
